sudo: required
services:
  - docker
language: node_js
node_js:
  - stable
env:
  - DAVE_VERSION=0.2.1
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
install:
  - sudo apt-get -y install docker-ce
  - npm install -g dave@"$DAVE_VERSION"
before_script:
  - dave build --context stable
script:
  - dave test --context stable
after_success:
  - docker login -u aa8y -p "$DOCKER_PASSWORD"
  - dave push --context stable
ignore:
  - "*.md"
